name: teste2
description: A new Flutter project.
version: 1.12.13+hotfix.6

environment:
  sdk: ">=2.1.0 <3.0.0"

module:
  androidX: true

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.2
  get: ^3.4.4
  flutter_icons: ^1.1.0
  # flutter_localizations:
  #   sdk: flutter
  # cloud_firestore: any
  # firebase_core: ^0.4.4
  # firebase_storage: any
  # firebase_auth: ^0.15.3
  # timeago: any
  # timeago_flutter: any
  # datetime_picker_formfield: any
  # date_format: ^1.0.8
  # image_picker: ^0.6.2+1
  # flutter_slidable: ^0.5.4
  # icon_shadow: ^1.0.1
  # url_launcher: ^5.4.1
  # flutter_rounded_progress_bar: ^0.1.2
  # flutter_staggered_animations: ^0.1.2
  # photo_view: ^0.9.0
  # google_maps_flutter: ^0.5.21+15
  # transparent_image: ^1.0.0
  # line_awesome_icons: ^1.0.4+2
  # flushbar:
  #   git:
  #     url: git://github.com/valterh4ck3r/flushbar
  #     ref: master
  # flutter_svg:
  # flare_flutter: ^2.0.1
  # firebase_admob: ^0.9.1
  # youtube_player_flutter: ^6.0.3+2
  # firebase_messaging: any
  # google_sign_in: ^4.2.0
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  


flutter:
  uses-material-design: true

  # assets:
    # - lib/style/images/noticias.jpg
    # - lib/style/images/atracoes.jpg
    # - lib/style/images/gastronomia.jpg
    # - lib/style/images/emprego.jpg
    # - lib/style/images/sobre.png
    # - lib/style/images/logo.png
    # - lib/style/images/noticias-categorias/todas-noticias.svg
    # - lib/style/images/erro/acesso-negado.png
    # - lib/style/images/icones_fonte/observatorio.png
    # - lib/style/images/icones_fonte/difusora.png
    # - lib/style/images/icones_fonte/tonogiro.png
    # - lib/style/images/icones_fonte/folhadeouro.png
    # - lib/style/images/icones_fonte/g1.png
    # - lib/style/dark-map.json
    # - lib/style/images/emBreve.png
    # - lib/style/splash.flr


  fonts:
    - family: PoppinsBold
      fonts:
        - asset: assets/fonts/Poppins/Poppins-Bold.ttf

    - family: PoppinsExtraBold
      fonts:
        - asset: assets/fonts/Poppins/Poppins-ExtraBold.ttf

    - family: PoppinsSemiBold
      fonts:
        - asset: assets/fonts/Poppins/Poppins-SemiBold.ttf

    - family: OSLight
      fonts:
        - asset: assets/fonts/Open_Sans/OpenSans-Light.ttf

    - family: OSRegular
      fonts:
        - asset: assets/fonts/Open_Sans/OpenSans-Regular.ttf

