name: teste2
description: A new Flutter project.
version: 1.12.13+hotfix.6

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cloud_firestore: ^0.13.0+1
  firebase_core: ^0.4.3+1
  firebase_storage: ^3.1.0
  firebase_auth: ^0.15.3
  timeago: any
  datetime_picker_formfield: any
  date_format: ^1.0.8
  image_picker: ^0.6.2+1
  flutter_slidable: ^0.5.4
  responsive_container: ^0.0.1
  icon_shadow: ^1.0.1
  url_launcher: ^5.4.1
  flutter_rounded_progress_bar: ^0.1.2
  flutter_staggered_grid_view: ^0.3.0
  flutter_staggered_animations: "^0.1.2"
  photo_view: ^0.9.0
  google_maps_flutter: ^0.5.21+15
  geolocator: ^5.1.5
  transparent_image: ^1.0.0
  get: ^1.6.3
  line_awesome_icons: ^1.0.4+2
  flushbar: ^1.9.1
  splashscreen: ^1.2.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  cupertino_icons: ^0.1.2


flutter:

  uses-material-design: true

  assets:
    - lib/style/images/noticias.jpg
    - lib/style/images/atracoes.jpg
    - lib/style/images/gastronomia.jpg
    - lib/style/images/sobre.png
    - lib/style/images/logo.png
    - lib/style/images/noticias-categorias/todas.jpg
    - lib/style/images/noticias-categorias/cidade.jpg
    - lib/style/images/noticias-categorias/denuncia.jpg
    - lib/style/images/noticias-categorias/cultura.jpg
    - lib/style/images/noticias-categorias/educacao.jpg
    - lib/style/images/noticias-categorias/economia.jpg
    - lib/style/images/noticias-categorias/esporte.jpg
    - lib/style/images/noticias-categorias/policia.png
    - lib/style/images/noticias-categorias/politica.jpg
    - lib/style/images/noticias-categorias/turismo.jpg
    - lib/style/images/erro/nenhuma-noticia.png
    - lib/style/images/erro/acesso-negado.png
    - lib/style/dark-map.json
    - lib/style/images/emBreve.png


  fonts:
    - family: Gilroy-Bold
      fonts:
        - asset: fonts/Gilroy-Bold.ttf

    - family: Gilroy-Heavy
      fonts:
        - asset: fonts/Gilroy-Heavy.ttf
    
    - family: Gilroy-Light
      fonts:
        - asset: fonts/Gilroy-Light.ttf

    - family: Gilroy-Medium
      fonts:
        - asset: fonts/Gilroy-Medium.ttf

    - family: Gilroy-Regular
      fonts:
        - asset: fonts/Gilroy-Regular.ttf

    - family: Gilroy-Black
      fonts:
        - asset: fonts/Gilroy-Black.ttf

    - family: SourceSansPro-Light
      fonts:
        - asset: fonts/SourceSansPro-Light.ttf

    - family: SourceSansPro-Regular
      fonts:
        - asset: fonts/SourceSansPro-Regular.ttf


